config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :pizzas, except: [:new, :edit, :update, :show]
    get 'prepare', to: "pizzas#check_orderable"
    patch 'pizzas', to: "pizzas#update"
    patch 'add_ingredient', to: "pizzas#add_item"
    delete 'del_ingredient', to: "pizzas#remove_item"
  end

  get '/supervizor/order/:id/process', to: 'visitors#start'
  get '/supervizor/order/:id/deliver', to: 'visitors#finish'
  get '/supervizor/order/:id/pdf', to: 'visitors#download'

  get 'thank_you', to: 'visitors#thank_you'
  patch 'confirm', to: 'visitors#confirm_verified_order'
  delete 'reset', to: 'visitors#destroy_order'
  root to: 'visitors#index'

  devise_for :users
  mount RailsAdmin::Engine => '/supervizor', as: 'rails_admin'
end

app/controllers/visitors_controller.rb
require 'pdf_generator'

class VisitorsController < ApplicationController
  before_filter :get_actual_order, except: [:index, :download, :finish, :start ]

  def index
    @user = current_or_guest_user
    @order = @user.orders.last || Order.new()
    @ingredients = Ingredient.group_by_category
  end

  def destroy_order
    @order.destroy
    redirect_to :root
  end

  def confirm_verified_order
    current_or_guest_user.address = Address.create(secure_params)
    @order.update( pdf_is_avaliable: PdfGenerator.create_doc(@order))
    @order.buy_pizza!
    reset_session
    redirect_to :thank_you
  end

  def thank_you
  end

  # faked admin methods
  def start
    order = Order.find(params[:id])
    if order.pdf_is_avaliable.present?
      order.bake_pizza!
      redirect_to '/supervizor/order'
    else
      head :no_content
    end
  end

  def download
    order = Order.find(params[:id])
    if order.pdf_is_avaliable.present?
      send_file order.pdf_url
    else
      head :no_content
    end
  end

  def finish
    order = Order.find(params[:id])
    if order.pdf_is_avaliable.present?
      order.deliver_pizza!
      redirect_to '/supervizor/order'
    else
      head :no_content
    end
  end


  private

  def get_actual_order
    @order = current_or_guest_user.orders.last
  end

  def secure_params
    params.require(:address).permit([:name, :firstname, :street, :city, :phone, :mobile])
  end
end

app/views/visitors/_address_form.html.haml
= simple_form_for( @user, url: confirm_path ,  html: { class: 'form-horizontal' }, wrapper: :horizontal_form ) do |form|
  %h1
    Lieferanschrift
  / = form.input :email, placeholder: 'E-Mail'
  = simple_fields_for :address, wrapper: :horizontal_form do |address|
    = address.input :firstname, placeholder: 'Vorname'
    = address.input :name, placeholder: 'Nachname'
    = address.input :street, placeholder: 'Strasse & Hausnummer'
    = address.input :city, placeholder: 'Ort'
    = address.input :phone, placeholder: 'Telefon'
    = address.input :mobile, placeholder: 'Mobilnummer'
  = form.submit('Bestellen', class: 'btn-lg pull-right')
#error_display

app/views/visitors/index.html.haml
#presenter.carousel.slide{ data: { ride: "carousel" , wrap: 'false', interval: 'false', user: @user.email , token: @user.authentication_token }}
  .carousel-inner{role: 'listbox'}
    .item.active#select
      .carousel_body
        .container
          #get_size
            = create_or_update_size
    .item#configure
      .carousel_body
        .container-fluid
          %ul.nav.nav-tabs#ingredient_selector
            - @ingredients.keys.reverse.each_with_index do |key, index|
              %li{ role: 'presentation', class: ( index == 0 ? 'active' : '') }= link_to(key, '#', data: { ref: key_identifier(key) })
        .container-fluid.gap
          .ingredient_list{ data: { offset: 0,  target: "#ingredient_nav" }}
            .row
              = customize_boxes
          %ul#purchased_items
            - if current_pizza.present?
              - current_pizza.pizza_items.each do |item|
                - if item.ingredient.is_default
                  %li
                    %p= [content_tag(:b){item.ingredient.name}, '<br/>', content_tag(:small){item.ingredient.category}].join().html_safe
                - else
                  %li{ data: { category: key_identifier( item.ingredient.category ), sibling: item.ingredient.sibling } }
                    = link_to( [content_tag(:span, class: 'glyphicon glyphicon-remove-circle'){} , content_tag(:b){item.ingredient.name}, '<br/>', content_tag(:small){item.ingredient.category}].join().html_safe , '#' )
    .item#checkout
      .carousel_body
        .container
          #summary.col-md-6.col-lg-6.col-sm-6.col-xs-6
            .item_notes
            .foot_notes
              %em.small
                Alle Kosten sind inklusive 2.5% Mehrwertsteuer
              .pull-right
                = link_to((content_tag(:span, class: 'glyphicon glyphicon-plus-sign' ){} + ' eine weitere Pizza hinzufügen').html_safe, '#', class: 'sec_link')
          #form.col-md-6.col-lg-6.col-sm-6.col-xs-6
            = render partial: 'address_form'
    %ol.nav.nav-pills.nav-justified.carousel-indicators
      %li.active{ data: { target: '#presenter', slide: { to: '0' }}}
        = link_to("Grösse<br/><span id='pizza_size', class='badge'>#{ current_pizza ? t(current_pizza.size) : '?' }</span>".html_safe, '#' )
      %li{ configure_links_to }
        = link_to("Zutaten<br/><span id='addon_collector' class='badge'>#{ current_pizza ? current_pizza.pizza_items.count - Ingredient.default.count : 0 }</span>".html_safe, '#' )
      %li{ checkout_links_to }
        = link_to("Kasse<br/><span id='pizza_price', class='badge'>#{ current_pizza ? number_to_currency(current_pizza.total) : 'CHF 0.00'}</span>".html_safe, '#')
  %ul#finalize.nav.nav-bar
    %li= link_to('<span class="glyphicon glyphicon-remove-circle"></span> Bestellung stornieren'.html_safe, reset_path, method: :delete, class: @order.persisted? ? '' : 'hidden')

app/views/visitors/thank_you.html.haml
#final_message.panel.panel-default
  .panel-heading
    %h2
      Vielen Dank, dass sie bei uns eingekauft haben.
  .panel-body
    Beehren Sie uns bald wieder
    %p
      Ihr pitprone Team
  .panel-footer
    = link_to('zurück zur Bestellseite', root_path )